/*
 * biop.h
 */
typedef struct Packet Packet;

int biOp(int op, Packet* p1, Packet* p2);

void convError(void);
void int2float(Packet* p);
void int2str(Packet* p);
void char2int(Packet* p);
void char2float(Packet* p);
void char2str(Packet* p);
void float2str(Packet* p);
void float2int(Packet* p);
void str2int(Packet* p);
void str2float(Packet* p);

void char_plus(Packet* p1, Packet* p2);
void float_plus(Packet* p1, Packet* p2);
void str_plus(Packet* p1, Packet* p2);
void int_plus(Packet* p1, Packet* p2);
void int_minus(Packet* p1, Packet* p2);
void int_mod(Packet* p1, Packet* p2);
void char_minus(Packet* p1, Packet* p2);
void float_minus(Packet* p1, Packet* p2);
void str_minus(Packet* p1, Packet* p2);
void char_mod(Packet* p1, Packet* p2);
void float_mod(Packet* p1, Packet* p2);
void str_mod(Packet* p1, Packet* p2);
void int_mult(Packet* p1, Packet* p2);
void char_mult(Packet* p1, Packet* p2);
void float_mult(Packet* p1, Packet* p2);
void str_mult(Packet* p1, Packet* p2);
void int_div(Packet* p1, Packet* p2);
void char_div(Packet* p1, Packet* p2);
void float_div(Packet* p1, Packet* p2);
void str_div(Packet* p1, Packet* p2);
void int_eq(Packet* p1, Packet* p2);
void char_eq(Packet* p1, Packet* p2);
void float_eq(Packet* p1, Packet* p2);
void str_eq(Packet* p1, Packet* p2);
void int_ne(Packet* p1, Packet* p2);
void char_ne(Packet* p1, Packet* p2);
void float_ne(Packet* p1, Packet* p2);
void str_ne(Packet* p1, Packet* p2);
void int_lt(Packet* p1, Packet* p2);
void char_lt(Packet* p1, Packet* p2);
void float_lt(Packet* p1, Packet* p2);
void str_lt(Packet* p1, Packet* p2);
void int_le(Packet* p1, Packet* p2);
void char_le(Packet* p1, Packet* p2);
void float_le(Packet* p1, Packet* p2);
void str_le(Packet* p1, Packet* p2);
void int_gt(Packet* p1, Packet* p2);
void char_gt(Packet* p1, Packet* p2);
void float_gt(Packet* p1, Packet* p2);
void str_gt(Packet* p1, Packet* p2);
void int_ge(Packet* p1, Packet* p2);
void char_ge(Packet* p1, Packet* p2);
void float_ge(Packet* p1, Packet* p2);
void str_ge(Packet* p1, Packet* p2);
void int_and(Packet* p1, Packet* p2);
void char_and(Packet* p1, Packet* p2);
void float_and(Packet* p1, Packet* p2);
void str_and(Packet* p1, Packet* p2);
void int_or(Packet* p1, Packet* p2);
void char_or(Packet* p1, Packet* p2);
void float_or(Packet* p1, Packet* p2);
void str_or(Packet* p1, Packet* p2);
