/*
 * class        : generic
 * superClass	: cosmic
 *
 *
 */
#include "cl_cosmic.h"

extern ClassInfo class_generic;
long helper_generic_get();
long helper_generic_set();
extern int flag_cliprompt;

long meth_generic_GB_copy();
long meth_generic_GB_data();
long meth_generic_GB_char();
long meth_generic_GB_count();
long meth_generic_GB_create();
long meth_generic_GB_decChar();
long meth_generic_GB_decChar1();
long meth_generic_GB_decLine();
long meth_generic_GB_free();
long meth_generic_GB_herePtr();
long meth_generic_GB_incChar();
long meth_generic_GB_incChar1();
long meth_generic_GB_incLine();
long meth_generic_GB_line();
long meth_generic_GB_moveToChar();
long meth_generic_GB_moveToLine();
long meth_generic_GB_moveToStart();
long meth_generic_GB_nthChar();
long meth_generic_GB_nthLine();
long meth_generic_GB_set();
long meth_generic_GB_setCopy();
long meth_generic_SGMLBuildDoc();
long meth_generic_SGMLBuildDocB();
long meth_generic_SGMLBuildDoc_flush();
long meth_generic_SGMLBuildDoc_insertObj();
long meth_generic_SGMLBuildDoc_setBuff();
long meth_generic_SGMLBuildDoc_setColors();
long meth_generic_SGMLBuildDoc_span();
long meth_generic_SGMLFindAnchorOffset();
long meth_generic_SGMLGetStyle();
long meth_generic_SGMLMathFormater();
long meth_generic_SGMLReBuildDoc();
long meth_generic_SGMLSetStyle();
long meth_generic_SGMLTableFormater();
long meth_generic_SGMLTileDoc();
long meth_generic_STGInfo();
long meth_generic_STG_clean();
long meth_generic_STG_tagPtr();
long meth_generic_STG_attrEx();
long meth_generic_STG_attr();
long meth_generic_accessible();
long meth_generic_activeHelp();
long meth_generic_after();
long meth_generic_alarm();
long meth_generic_append();
long meth_generic_argument();
long meth_generic_ascii();
long meth_generic_asciiVal();
long meth_generic_bell();
long meth_generic_bellVolume();
long meth_generic_char();
long meth_generic_childn();
long meth_generic_clear();
long meth_generic_clone();
long meth_generic_clone2();
long meth_generic_cli();
long meth_generic_color();
long meth_generic_cos();
long meth_generic_compressSpaces();
long meth_generic_concatenate();
long meth_generic_concatList();
long meth_generic_countChildren();
long meth_generic_countItems();
long meth_generic_countLines();
long meth_generic_countWords();
long meth_generic_ctrlKeyP();
long meth_generic_cursorShape();
long meth_generic_cycleColors();
long meth_generic_date();
long meth_generic_deepObjectListSend();
long meth_generic_defineNewFont();
long meth_generic_delay();
long meth_generic_deleteFile();
long meth_generic_deleteSubStr();
long meth_generic_deleteSubStrQ();
long meth_generic_depth();
long meth_generic_destroyVariable();
long meth_generic_environVar();
long meth_generic_filter();
long meth_generic_findPattern();
long meth_generic_float();
long meth_generic_format();
long meth_generic_freeSelf();
long meth_generic_get();
long meth_generic_getResource();
long meth_generic_getSelection();
long meth_generic_getVariable();
long meth_generic_gravity();
long meth_generic_hash();
long meth_generic_height();
long meth_generic_initialize();
long meth_generic_int();
long meth_generic_isBlank();
long meth_generic_item();
long meth_generic_key();
long meth_generic_listAllObjects();
long meth_generic_loadFile();
long meth_generic_loadSTG();
long meth_generic_lower();
long meth_generic_makeTempFile();
long meth_generic_not();
long meth_generic_nthChar();
long meth_generic_nthChild();
long meth_generic_nthItem();
long meth_generic_nthLine();
long meth_generic_nthObjectInList();
long meth_generic_nthSibling();
long meth_generic_nthWord();
long meth_generic_objectListAppend();
long meth_generic_objectListAppend_children();
long meth_generic_objectListCount();
long meth_generic_objectListCount_children();
long meth_generic_objectListDelete();
long meth_generic_objectListDelete_children();
long meth_generic_objectListPrepend();
long meth_generic_objectListPrepend_children();
long meth_generic_objectListSend();
long meth_generic_objectListSend_children();
long meth_generic_objectPosition();
long meth_generic_parent();
long meth_generic_pipe();
long meth_generic_prepend();
long meth_generic_print();
long meth_generic_printf();
long meth_generic_random();
long meth_generic_replaceChar();
long meth_generic_replaceCharQ();
long meth_generic_replaceStr();
long meth_generic_replaceStrQ();
long meth_generic_saveFile();
long meth_generic_scan();
long meth_generic_scanf();
long meth_generic_securityMode();
long meth_generic_self();
long meth_generic_selectionInfo();
long meth_generic_set();
long meth_generic_sendToInterface();
long meth_generic_setMouse();
long meth_generic_setResource();
long meth_generic_setSelection();
long meth_generic_setVariable();
long meth_generic_shiftKeyP();
long meth_generic_sin();
long meth_generic_sleep();
long meth_generic_sprintf();
long meth_generic_str();
long meth_generic_strlen();
long meth_generic_system();
long meth_generic_target();
long meth_generic_textWidth();
long meth_generic_trimEdge();
long meth_generic_trimEdgeQ();
long meth_generic_time();
long meth_generic_tool();
long meth_generic_x();
long meth_generic_unhash();
long meth_generic_version();
long meth_generic_violaPath();
long meth_generic_watch();
long meth_generic_width();
long meth_generic_word();
long meth_generic_writeln();
long meth_generic_y();
long meth_generic_HTTPCanonicalURL(VObj* self, Packet* result, int argc, Packet argv[]);
long meth_generic_HTTPCurrentDocAddr(VObj* self, Packet* result, int argc, Packet argv[]);
long meth_generic_HTTPCurrentDocAddrParsed(VObj* self, Packet* result, int argc, Packet argv[]);
long meth_generic_HTTPCurrentDocAddrSet(VObj* self, Packet* result, int argc, Packet argv[]);
long meth_generic_HTTPEncodeURL(VObj* self, Packet* result, int argc, Packet argv[]);
long meth_generic_HTTPDecodeURL(VObj* self, Packet* result, int argc, Packet argv[]);
long meth_generic_HTTPGet(VObj* self, Packet* result, int argc, Packet argv[]);
long meth_generic_HTTPGetNParse(VObj* self, Packet* result, int argc, Packet argv[]);
long meth_generic_HTTPPost(VObj* self, Packet* result, int argc, Packet argv[]);
long meth_generic_HTTPSubmit(VObj* self, Packet* result, int argc, Packet argv[]);
long meth_generic_HTTPHotListAdd(VObj* self, Packet* result, int argc, Packet argv[]);
long meth_generic_HTTPHotListChange(VObj* self, Packet* result, int argc, Packet argv[]);
long meth_generic_HTTPHotListDelete(VObj* self, Packet* result, int argc, Packet argv[]);
long meth_generic_HTTPHotListGet(VObj* self, Packet* result, int argc, Packet argv[]);
long meth_generic_HTTPHotListLoad(VObj* self, Packet* result, int argc, Packet argv[]);
long meth_generic_HTTPHotListSave(VObj* self, Packet* result, int argc, Packet argv[]);

long meth_generic_addPicFromFile(VObj* self, Packet* result, int argc,
                                 Packet argv[]); /* to support <IMG> */

long meth_generic_code_HTML_txt(VObj* self, Packet* result, int argc, Packet argv[]);
long meth_generic_code_HTML_txtAnchor(VObj* self, Packet* result, int argc, Packet argv[]);
long meth_generic_code_HTML_header_large(VObj* self, Packet* result, int argc, Packet argv[]);
long meth_generic_code_HTML_header_medium(VObj* self, Packet* result, int argc, Packet argv[]);
long meth_generic_code_HTML_header_small(VObj* self, Packet* result, int argc, Packet argv[]);
