
	switch (arg[0]) {
	case "doTelnet":
		/* arg[1]	normalized URL
		 */
		cmd = send("WWWTelnetHandler", "connect", arg[1]);
		system(cmd);
		return 1;
	break;
	case "doMailTo":
		/* arg[1]	normalized URL
		 */
		subject = concat("WWW mail from: ", arg[1]);
		tt = arg[1];
		i = findPattern(tt, "/");
		if (i == -1) {
			address = nthChar(tt, 7, 999);
			content = concat("This mail was generated by URL:\n",
					 tt, "\n");
		} else {
			address = nthChar(tt, 7, i-1);
			content = concat(nthChar(tt, i+1, 999), "\n");
		}
		tmpFile = makeTempFile();
		saveFile(tmpFile, content);

		cmd = concat("mail -s \"", subject,
				 "\" ", address, " < ", tmpFile);
		system(cmd);
		system(concat("rm ", tmpFile));
		return 1;
	break;
	}
	usual();
